### ISSUE TITLE
Sit does not work if "empty" hotbar slot in question was emptied by placing the item in it.

### ISSUE THREAD

**Issue by KandiPanda** [bl4ckscor3/Sit#1]
Did a test with a few things regarding the issue in the title.

1. Put one torch in an empty slot. Place the torch OR throw the torch. Attempt to sit using that slot. It will fail, but other slots will still work.
2. Start as in 1. Put any item in that slot after placing/throwing torch and remove it again. Slot will work again.
3. Start as in 1. Put armor in that slot, either with the cursor or from an armor stand, then attach armor to armor stand. Attempting to sit will fail.
4. Same as 3, except remove the armor from the slot manually with the cursor. Sitting will succeed. 
5. Start with a slot that Sit recognises as empty. Put armor in that slot, either with the cursor or from an armor stand, then attach armor to armor stand OR remove armor from slot with cursor. Either way will succeed.

It seems that it doesn't count the hotbar slot as "empty" unless the item is removed from the slot with the cursor, rather than by placing or throwing it, and putting armor on a stand doesn't change either state to the other?

**Comment by bl4ckscor3** [comment]
Does this file fix it for you?
[sit fix, unpack please.zip](https://github.com/bl4ckscor3/Sit/files/2472612/sit.fix.unpack.please.zip)

**Comment by KandiPanda** [comment]
Seems to fix the issue, yeah. Thanks. \^_\^ 

Hopefully the info I left helped narrow down what was causing it? (It sounded like other people were encountering it without realising the cause, and on one server I go on, someone had been relogging because they didn't realize that dropping an item in the slot and removing it again was a workaround, so having it fixed is good.)

**Comment by bl4ckscor3** [comment]
Yup, the info provided was very helpful :)
