### ISSUE TITLE
Sitting on 1.15.2 makes your legs not face the same direction as head except when looking south.

### ISSUE THREAD

**Issue by DranDivine** [bl4ckscor3/Sit#10]
When trying to sit, no matter if it's on slabs or stairs, your legs won't face the direction you are looking except when looking south. I have included pictures of me looking in all directions. in order E-N-W-S
![2020-05-25_16 50 29](https://user-images.githubusercontent.com/64855209/82823754-6f773880-9ea8-11ea-8c68-8ac6730491b1.png)

![2020-05-25_16 50 20](https://user-images.githubusercontent.com/64855209/82823745-6dad7500-9ea8-11ea-92b9-6c7491b19710.png)

![2020-05-25_16 50 25](https://user-images.githubusercontent.com/64855209/82823740-6b4b1b00-9ea8-11ea-929c-d386edf91850.png)

![2020-05-25_16 50 26](https://user-images.githubusercontent.com/64855209/82823729-68502a80-9ea8-11ea-875d-bddfc9934f0c.png)

**Comment by bl4ckscor3** [comment]
Using Forge 31.2.0 and Sit v1.3, my legs are moving all the time when I'm turning around. I notice that you are using OptiFine, so it's very likely that that one is causing the issue.
