### ISSUE TITLE
[fabric-1.16.1] Sitting from staircase to staircase doesn't remove the sit entity

### ISSUE THREAD

**Issue by NeeEoo** [bl4ckscor3/Sit#11]
This has made it so i cant place a block at that place

Command `/data get entity @e[type=sit:entity_sit,limit=1,sort=nearest]`

prints this

`entity.sit.entity_sit has the following entity data: {NoGravity: 1b, Motion: [0.0d, 0.0d, 0.0d], FallDistance: 0.0f, Pos: [-260.5d, 63.25d, 151.01050000002374d], Fire: -1s, Invulnerable: 0b, Air: 300s, OnGround: 0b, PortalCooldown: 0, UUID: [I; 905823746, -2079178538, -1215937010, -911088620], Rotation: [6.0266237f, 0.0f]}`

There are 11 of those sit entities in my world and I'm unable to use the kill command to remove them.

I used the staircase to sit on another staircase without dismounting

**Comment by bl4ckscor3** [comment]
I have changed it so that players can now only sit when they are not already sitting, and rightclicking the top face of a stairs/slab block.
[This has been the case in the Forge version of Sit for a while](https://www.curseforge.com/minecraft/mc-mods/sit/files/2795596).

**Comment by NeeEoo** [comment]
Would you also be able to build and publish a 1.16.1 version of Sit to curseforge.

**Comment by bl4ckscor3** [comment]
I do not see a reason not to update to 1.16.2, no. Not sure if the version I published today works for 1.16.1, but you can try it out.

**Comment by NeeEoo** [comment]
I just checked it works for 1.16.1
