### ISSUE TITLE
[fabric-1.16.x] Unable to place any block unless its placed on the top side of a block

### ISSUE THREAD

**Issue by NeeEoo** [bl4ckscor3/Sit#12]
Unable to place any blocks on a full block on the sides.

This is the line causing the bug https://github.com/bl4ckscor3/Sit/blob/1.16-fabric/src/main/java/bl4ckscor3/mod/sit/Sit.java#L40

**Comment by bl4ckscor3** [comment]
Fuck, that is a stupid oversight. Sorry about that.
