### ISSUE TITLE
Suggestion: Hotkey for sitting?

### ISSUE THREAD

**Issue by muzikbike** [bl4ckscor3/Sit#13]
As to allow for sitting on any block at any time, rather than having to right click specifically on stairs and slabs.

Would probably cause the player to sit forever until a movement key is pressed, after which point they would start standing.

**Comment by bl4ckscor3** [comment]
I don't want this mod to be a "sit on everything" mod. I only want the player to be able to sit on slabs and stairs.

Being able to press a movement key to stop sitting will not be happening, as the way I make the player sit down is the same way that Minecraft uses to let the player ride horses/pigs/minecarts/etc.
