### ISSUE TITLE
suggestion: Ability to lie on blocks

### ISSUE THREAD

**Issue by muzikbike** [bl4ckscor3/Sit#14]
The animation is already there for sleeping:
![2020-11-12_00 53 43](https://user-images.githubusercontent.com/52297970/98881652-6d1e9000-2482-11eb-91e5-b1f1dbd246a7.png)

Could possibly be done on any two adjacent slab blocks by right clicking (or given a dedicated hotkey like #13 to allow for it to be done anywhere).

Might be out of the scope of this mod though.

**Comment by bl4ckscor3** [comment]
Yes, it's out of scope.
