### ISSUE TITLE
Help the block is bugged with invisible armor_stand

### ISSUE THREAD

**Issue by OPdarmawan** [bl4ckscor3/Sit#17]
![image](https://user-images.githubusercontent.com/18474922/135774480-cf90862d-bcb2-44e8-a995-ff4dc058af7c.png)

help, I was just /sit in front of the fireplace, and somehow the invisible armor_stand stays under the block, cant be removed, cant put block on it or destroy a block..

**Comment by bl4ckscor3** [comment]
This mod does not add a `/sit` command, and does not spawn armor stands. My Sit mod in particular (https://www.curseforge.com/minecraft/mc-mods/sit-fabric) also has to be installed on the client and the server to work properly.
