### ISSUE TITLE
bug under the slab and staire when go up

### ISSUE THREAD

**Issue by Titoo8899** [bl4ckscor3/Sit#2]
Hi,
then I click right on a slab or a stair sit I. This is okay and works fine. But the I go up to move click I normal on the keyboard "shift". But in 99% of the move up bug the skin under the slab or in this slab then under the slab 1 or 2 blocks was. Please fix this.

**Comment by bl4ckscor3** [comment]
Do you mean that when you press SHIFT, you stand up, but get placed underground?
