### ISSUE TITLE
When I "dismount" I stuck in stairs and can see though textures until I jump/unstack

### ISSUE THREAD

**Issue by ghost** [bl4ckscor3/Sit#25]
Title

**Comment by bl4ckscor3** [comment]
When reporting bugs to mods, please always include the mod version and the Minecraft version.

**Comment by ghost** [comment]
1.12.2, latest

**Comment by bl4ckscor3** [comment]
"latest" is not a mod version.
But I don't support 1.12.2 anymore due to its age, so I'm sorry to say this won't be fixed.
