### ISSUE TITLE
Crashing when loading game, 1.18.2 forge loader 40.2.0

### ISSUE THREAD

**Issue by Lozf** [bl4ckscor3/Sit#27]
[latest.log](https://github.com/bl4ckscor3/Sit/files/10541189/latest.log)
[crashwrubidium.txt](https://github.com/bl4ckscor3/Sit/files/10541190/crashwrubidium.txt)

Thought it was genetic animals but a dev there tracked it down to this mod. It's kind of an odd crash!  Weirdly, it didn't begin crashing until William Wythers' was added but then it would always crash after, even with that mod removed.

**Comment by bl4ckscor3** [comment]
Because I can't reproduce this crash, please try if it still happens for you with this version of the mod, and tell me the results. That would be great, thanks! https://cdn.discordapp.com/attachments/402175060716158986/1069941935571222528/sit-1.18.2-1.3.3.jar
