### ISSUE TITLE
it is not working

### ISSUE THREAD

**Issue by eniogaming** [bl4ckscor3/Sit#29]
whenever i click on stairs nothing i downloaded the mod menu mod and it didn't show the mod i was playing 1.19.3

**Comment by bl4ckscor3** [comment]
If Mod Menu does not show you the mod, then you did not install the mod correctly. Make sure that you are using [the fabric version of Sit](https://www.curseforge.com/minecraft/mc-mods/sit-fabric/files/4297693).
