### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by JuanPacoPedrodelaMar** [bl4ckscor3/Sit#30]
When I try to join to a minecraft server on 1.20.1 (Fabric) it says that i have to install the mod on the client but i have already done that, idk why that happens

**Comment by bl4ckscor3** [comment]
Make sure both server and client have the same version installed. If that is the case, try disabling the version checker in the mod's config file.

**Comment by bl4ckscor3** [comment]
The version checker has been removed in the mod update to 1.20.5.
