### ISSUE TITLE
Falling to death

### ISSUE THREAD

**Issue by zc1108aaa** [bl4ckscor3/Sit#31]
Place blocks in the air, right-click to sit, sit away from the bottom, appear under half a block, will fall to death, cannot stand on the block

**Comment by bl4ckscor3** [comment]
Which version of Sit? Which Mod Loader? Which Minecraft version?

**Comment by zc1108aaa** [comment]
All versions are the same

**Comment by zc1108aaa** [comment]
The original version, ship, bed, mining car, and descent position are all optimized, but the descent position of this mod is not optimized

**Comment by bl4ckscor3** [comment]
I am asking you which version of Sit you are using, as well as which Minecraft version you are using. I'd also like to know if you are using Forge, NeoForge, Fabric, or Quilt.

**Comment by zc1108aaa** [comment]
Stand in the air when leaving, not on blocks

https://github.com/bl4ckscor3/Sit/assets/155424398/bca61a0b-07a8-478b-bac7-785b9d5fb335

1.20.6fabric-sit-1.20.5-26

**Comment by bl4ckscor3** [comment]
"Sit" always puts you back where you clicked the slab from. This is in order to prevent sitting being abused. It's supposed to be purely cosmetic, and not give any gameplay advantage. As far as I can tell, the behavior you see is intentional.
