### ISSUE TITLE
Glitching into stairs while sitting

### ISSUE THREAD

**Issue by Silent-Mouse** [bl4ckscor3/Sit#33]
![2024-05-24_15 09 10](https://github.com/bl4ckscor3/Sit/assets/170683032/9e1ce10c-8728-4b8e-bf45-fade3af977ad)

**Comment by bl4ckscor3** [comment]
Which Minecraft and Sit version are you using? Fabric or (Neo-)Forge?

**Comment by Silent-Mouse** [comment]
Neoforge
