### ISSUE TITLE
Will not run on 1.20

### ISSUE THREAD

**Issue by VigilanteReal** [bl4ckscor3/Sit#35]
Upon booting up a get an error message saying that the mod is incompatible with 1.20 and that it requires a version of Minecraft 1.20.1
![Capture](https://github.com/bl4ckscor3/Sit/assets/85533134/71829be8-12b3-4de2-ae14-fb3284614fa0)

**Comment by bl4ckscor3** [comment]
This has nothing to do with Sit. You need to make sure to install [the proper version of KilnReborn](https://www.curseforge.com/minecraft/mc-mods/kilnreborn/files/5224410).
