### ISSUE TITLE
Getting up in certain blocks inside them

### ISSUE THREAD

**Issue by LumeMC** [bl4ckscor3/Sit#39]
When a player sits down and the block they were standing on is not a full block (such as slabs, dirt paths and more), standing up from a sitting position causes the player to stand inside the block.

Minecraft version: 1.19.2, forge 43.4.6
Mod version: 1.3.3

**Comment by bl4ckscor3** [comment]
Duplicate of #32. When this was fixed I already no longer supported 1.19.2, meaning the fix wasn't applied for that version I'm afraid.
