### ISSUE TITLE
Sit 1.2+ conflicts with ArchitectureCraft .98 

### ISSUE THREAD

**Issue by MineCrak** [bl4ckscor3/Sit#4]
Hello, love your mod and the people on the Cubic Chunks server get a lot of use out of it. 

We are also very happy that you chose to add ArchitectureCraft compatibility with Sit v1.2+. Which works fine so far as we can tell with AC .80 which is what everyone has used for a long time. 

Unfortunately that compatibility code conflicts with the new version .98 of AC. Also unfortunately we didn't notice that until after we had updated AC to .98 on our server. And as I have also found through testing, it's impossible to roll back to AC .80 once a map has been exposed to AC .98, all kinds of b0rking occurs if you do. 

Our only option at this point is to role Sit back to v1.1.2, which does seem to at least co-exist with AC .98 ok, or update Sit to an as yet not existing version that fixes this. I've already fully explored the AC rollback option and that is a no-go. 

The people on my server really really want Sit+AC compat though due to so much use of both and new huge structures being built that will greatly benefit from that compatibility. So I hope this is something that can be fixed. :)
---------------------------------------------------
The problems:

1) A percentage of the time, not every time; placing an AC block won't work and it will have to be placed more than once or twice to get it to stick. We are calling it AC-Lag.

2) A percentage of the time, not every time; an already placed AC block will either completely disappear or change into another AC block when a block is placed next to it. Might just be when other AC blocks are placed next to it, but I don't think so.

3) A placed AC block will simply disappear over time with no recalled interaction. 

-----

Another server member, TwistedZero, did some troubleshooting on this and said:
"Hmm, I get the issue if I place any block while looking at an ArchitectureCraft Block?"

**Comment by MineCrak** [comment]
I can't edit my first post, I think because of my browser version or something. 

Not sure why that one section is bolded, but it wasn't intentional.

**Comment by MineCrak** [comment]
Also, I tested Sit v1.2.4 with AC .98 and the problem still exists.

**Comment by MineCrak** [comment]
Crud.. v1.2.3

**Comment by bl4ckscor3** [comment]
Thank you for the report. Some code from ArchitectureCraft that I was using changed, which in turn broke compatibility. Sit v1.2.4 should fix it.

Also, that section is bold because `---` below a line will result in that line being treated as a header.

**Comment by MineCrak** [comment]
Fantastic! Thank you. And if you want to check out the server just let me know.

**Comment by MineCrak** [comment]
Also; I know you already closed the issue about this other problem and I understand why, but I feel it's important to let you know how bad it is.

The problem of accidentally sitting and then falling through a slab has affected some of my players so often that this group has been clamoring for the complete removal of Sit mod. The server is divided over it. 

The problem is especially bad up in the server's space orbit where it is very useful to use slabs to keep Space Spiders from spawning, but also is a problem because falling from 2000y every time becomes a major drama.

**Comment by bl4ckscor3** [comment]
It's not really something I can do anything about. Vanilla Minecraft handles the position finding after dismounting and, at least as far as I know, there is nothing exposed to hook into that.
