### ISSUE TITLE
[Feature Request] Support for language translations

### ISSUE THREAD

**Issue by Greg-21** [bl4ckscor3/Sit#6]
Currently this mod doesn't have a support for translations, and all strings that could be translatable are hard-coded now. Honestly, the support for translations wasn't needed until the new config option was released a few days ago, and since then I think it would be great to be able to translate.

Additionally, the "block_reach_distance" phrase on the in-game configuration screen looks like an internal name, so probably it should be changed to something more representative.

Screenshot showing the in-game config screen (from Sit 1.3 for MC 1.12.2):
![Sit-mod-configuration-screen](https://user-images.githubusercontent.com/34160838/71514514-2f7f3b80-289f-11ea-904a-82c6fa09a973.png)

**Comment by bl4ckscor3** [comment]
In newer versions translating isn't possible. I could only change this for 1.12.2 but I want the versions to be as similar as possible. As for the "internal name": Removing the underscores to have it read "Block Reach Distance" is superfluous. You can still read what it means with the current way, right? So that shouldn't be that big of a problem :)

**Comment by Greg-21** [comment]
I'm not a Minecraft modder, so my information here may be not correct, but as far as I know mod translations are possible in Minecraft versions newer than 1.12.2. However, I agree that the Forge in-game configuration screens are untranslatable in newer Forge versions, but it's due to the fact that they... are simply nonexistent there. Unfortunately I don't know whether Forge will have at all its in-game configuration screens back, or not. If the answer is "yes", I think you could leave my feature request open until a new/ported old Forge in-game configuration screens are ready :)

As for the "internal" name, you are right that it does its job, but you can't deny that a capitalized sentence without the underscores will look much more elegant than its counterpart. Even such small and simple mod like mezz's Mod Name Tooltip has its "internal" name replaced, so I think it shouldn't be hard to implement.

**Comment by bl4ckscor3** [comment]
Newer Forge versions support configuration screens, but they have to be custom made by the modder and there is no built-in screen like in 1.12.2. While there is the option in 1.13+ to add a translation key to a configuration option, it is not used anywhere. Someone is working on an automatic configuration screen for 1.15.1, and they might make translations possible. You're correct that I should have left the issue open to remind myself to add this later on when support for it is back in Forge. Sorry about that.

**Comment by Greg-21** [comment]
You know what? I got used to the nice new TOML-based Forge configuration system (which doesn't support translations at all and IMO doesn't need to), and now 1.12 is considered obsolete by many people, so I don't care anymore.
