### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by axin0452** [bl4ckscor3/Sit#7]
Can you add a shortcut key to trigger sit down, instead of specifying a seat on a block, so that the player can sit on any block, such as a chair that cannot be seated in the mod, the player can pass this mod To perform a sit down, so that the player can sit down, so that the player can sit down at any time.
Reference: http://mod-minecraft.net/simply-sit-mod/

**Comment by bl4ckscor3** [comment]
No, I don't want the player to be able to sit down anywhere. If you want support for a specific mod's chair/slab/stairs block, please tell me so and I'll see what I can do.
