### ISSUE TITLE
[Feature request] Manual/Automatic mode

### ISSUE THREAD

**Issue by Matthysse** [bl4ckscor3/Sit#9]
Hello!

It would be nice to add a switch to choose between the "automatic" mode (when the player clikcs on the stairs/slabs he sits) or in "manual" mode (the player must use a key binding in the controls to sit). It would be used for blocks added withs mods, or just for relaxing where we want (as the SimpleSit plugin is no longer updated).

**Comment by bl4ckscor3** [comment]
I don't want this mod to allow the player to sit down anywhere.
